# Generated by Django 5.0.1 on 2024-05-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
