# Generated by Django 5.0.1 on 2024-05-31 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_date_creaeted_expense_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='yearly_income',
            new_name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='finishDate',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='timeSpan',
        ),
        migrations.AddField(
            model_name='goal',
            name='activeFor',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goal',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
