# Generated by Django 5.0.1 on 2024-06-04 19:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_rename_yearly_income_goal_monthly_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_name',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
