# Generated by Django 5.0.1 on 2024-06-04 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_goal_goal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='monthly_income',
            new_name='monthly_budget',
        ),
    ]
